### ISSUE TITLE
大神能不能给一个和content_size一起使用的模板啊

### ISSUE THREAD

**Issue by matthkewk** [Juszoe/flexget-nexusphp#43]
自己琢磨了很久都没有成功……请大神来个模板我好自己修改一下，非常感谢

**Comment by Juszoe** [comment]
按照正常设置就好了呀，你是怎么写的？
``` yaml
tasks:
  my-task:
    rss: 
      url: https://www.example.com/rss.xml
      other_fields:
        - link
    nexusphp:
      cookie: ''
      discount:
        - free
        - 2xfree
    content_size:
      min: 12
      max: 1200
    download: ~/flexget/torrents/
```
