### ISSUE TITLE
U2这配置哪里出错了

### ISSUE THREAD

**Issue by mylovesaber** [Juszoe/flexget-nexusphp#49]
最新版本的插件
配置部分：
```yaml
  u2free:
    rss:
      url: xxx
      other_fields: [link]
    nexusphp:
      cookie: 'aaa'
      discount:
        - free
        - 2xfree
      seeders:
        min: 0
        max: 2
      hr: no
```
log显示不管是不是free或者2xfree或者2.33一律被reject了，一律提示不满足优惠规则
