### ISSUE TITLE
Task doesn't have any output plugins, you should add (at least) one!

### ISSUE THREAD

**Issue by maodreamer** [Juszoe/flexget-nexusphp#59]
config.yml:

```yml
web_server:
  bind: 0.0.0.0
  port: 3539

schedules:
  - tasks: [ pth ]
    interval:
      minutes: 10

templates:
  qb:
    qbittorrent:
      host: *.*.*.*
      port: 8080
      username: ***
      password: ***

  freespace:
    free_space:
      path: /home/
      space: 10240

  size:
    content_size:
      min: 6000
      max: 600000
      strict: no

tasks:
pth:
  rss:
    url: https://pthome.net/torrentrss.php?rows=10&exp=90&passkey=*********
    other_fields:
      - link
  nexusphp:
    cookie: '*********'
    discount:
      - free
      - 2xfree
    seeders:
      min: 0
      max: 10
    leechers:
      min: 0
      max: 200
      max_complete: 0.8
    left-time: 23 hours
    hr: no
    adapter: 
      free: free
      2x: twoup
      2xfree: twoupfree
      30%: thirtypercent
      50%: halfdown
      2x50%: twouphalfdown
    comment: no
    user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
    remember: yes
    qbittorrent:
      host: *.*.*.*
      port: 8080
      username: ***
      password: ***
      path: ~/flexget/torrents/
```

flexget.log:

2021-02-28 15:18:17 INFO     manager                       Test mode, creating a copy from database ...
2021-02-28 15:18:23 VERBOSE  manager                       Creating new database /root/.flexget/test-config.sqlite - DO NOT INTERRUPT ...
2021-02-28 15:19:10 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2021-02-28 15:19:12 VERBOSE  details       pth             Produced 10 entries.
2021-02-28 15:19:14 VERBOSE  task                          ACCEPTED: `Jade 無可比擬的演藝泰斗 永遠懷念 吳孟達 HDTV 1080i H264 DD5.1-PTHtv` by nexusphp plugin
2021-02-28 15:19:15 VERBOSE  task                          ACCEPTED: `Dead Man 1995 1080p BluRay x265 10bit DTS-PTH` by nexusphp plugin
2021-02-28 15:19:15 VERBOSE  task                          ACCEPTED: `Dead Man 1995 1080p BluRay x264 DTS-PTH` by nexusphp plugin
2021-02-28 15:19:15 VERBOSE  task                          ACCEPTED: `Sex Explained NF WEB-DL 1080p x264 DDP5.1-PTHweb` by nexusphp plugin
2021-02-28 15:19:16 VERBOSE  task                          ACCEPTED: `Street Food Asia S01 NF WEB-DL 1080p x264 DDP5.1 Atmos-PTHweb` by nexusphp plugin
2021-02-28 15:19:17 VERBOSE  task                          ACCEPTED: `Street Food Latin America S01 NF WEB-DL 1080p x264 DDP5.1 Atmos-PTHweb` by nexusphp plugin
2021-02-28 15:19:17 VERBOSE  task                          ACCEPTED: `Dead Man 1995 1080p BluRay Remux AVC DTS-HD MA 2.0-PTH` by nexusphp plugin
2021-02-28 15:19:17 INFO     remember_rej                  Remembering rejection of `Nuevo Orden 2020 1080p WEB-DL x264`
2021-02-28 15:19:17 VERBOSE  task                          REJECTED: `Nuevo Orden 2020 1080p WEB-DL x264` by nexusphp plugin because 50% does not match discount
2021-02-28 15:19:18 VERBOSE  task                          ACCEPTED: `The Other Man 2008 1080p Blu-ray AVC DTS-HD MA 5.1-Flynn@PTHome` by nexusphp plugin
2021-02-28 15:19:18 VERBOSE  task                          ACCEPTED: `The Casketeers S01 NF WEB-DL 1080p x264 AAC-PTHweb` by nexusphp plugin
2021-02-28 15:19:18 VERBOSE  details       pth             Summary - Accepted: 9 (Rejected: 1 Undecided: 0 Failed: 0)
2021-02-28 15:19:18 WARNING  task          pth             Task doesn't have any output plugins, you should add (at least) one!
2021-02-28 15:19:20 INFO     manager                       Removed test database

ubuntu 18.04
Python 3.8.5
