### ISSUE TITLE
u2的2xfree种识别为免费种

### ISSUE THREAD

**Issue by czqdavid** [Juszoe/flexget-nexusphp#63]
config.yml配置
```
u2:
  inputs:
    - limit:
        amount: 1
        from:
          rss:
            url: xxx
            other_fields:
               - link
  nexusphp:
    cookie: 'xxx'
    discount:
       - 2xfree
    seeders:
        min: 0
        max: 4
    remember: no
```
flexget.log输出(最近U2全站2xfree)
```
REJECTED: `xxx` by nexusphp plugin because free does not match discount
```
在discount加入free后，正常。目前感觉U2的2xfree直接被free的判断识别了。
