### ISSUE TITLE
hdchina 匹配不到免费种 是我设置错误吗

### ISSUE THREAD

**Issue by chinatengjie** [Juszoe/flexget-nexusphp#71]
by remember_rejected plugin because rejected on behalf of nexusphp plugin: None does not match discount
识别匹配出现错误，有没有人遇到，或者说下怎么设置啊
匹配的这个
        2xfree: pro_free2up
        free: pro_free
UP

删除了匹配规则 可以了

**Comment by predest** [comment]
请问可以参考下是怎么设置的吗？我的就是不能下载免费种。以下为我的设置，不知道哪里出了问题。

    rss:
      url: 
      other_fields: [link]
    nexusphp:
      cookie: ''
      discount:
        - free
        - 2xfree
      left-time: 3 hours
      seeders:
        min: 0
        max: 2
      leechers:
        min: 5
        max: 10000
      hr: no
    content_size:
      min: 5120
      max: 204800
      strict: yes

**Comment by pengkaiwei** [comment]
同求配置，我的也不能下载免费种

**Comment by Juszoe** [comment]
刚刚测试HDC正常。
请不要自行设置`adapter`参数，这是在插件不兼容站点的情况下，自行兼容的一种方式。

**Comment by pengkaiwei** [comment]
> adapter
还希望大佬贴一下配置，下面是我的配置，识别免费有问题

https://gist.github.com/pengkaiwei/d5fab1599baa91d2bb65607519d2c74f

 hdc:
    rss:
      url: https://hd~~bf
      other_fields:
        - link
    template:
     - qb
     - size
    qbittorrent:
      label: hdc
    nexusphp:
      cookie: 'PHPSESSID=xx'
      discount:
        - free
        - 2xfree
      remember: no

**Comment by Juszoe** [comment]
@pengkaiwei  你的配置应该没问题，以下是我测试通过的配置
``` yaml
tasks:
  hdc:
    rss:
      url: https://hdchina.org/torrentrss.php?rows=10&linktype=dl&passkey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      other_fields:
        - link
    nexusphp:
      cookie: 'hdchina=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx; PHPSESSID=xxxxxxxxxxxxxxxxxx'
      discount:
        - free
        - 2xfree
```

**Comment by pengkaiwei** [comment]
> @pengkaiwei 你的配置应该没问题，以下是我测试通过的配置
> 
> ```yaml
> tasks:
>   hdc:
>     rss:
>       url: https://hdchina.org/torrentrss.php?rows=10&linktype=dl&passkey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
>       other_fields:
>         - link
>     nexusphp:
>       cookie: 'hdchina=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx; PHPSESSID=xxxxxxxxxxxxxxxxxx'
>       discount:
>         - free
>         - 2xfree
> ```

很奇怪的是，进hdc 看最近的种子（20分钟以内），有些自动下载了，也不是免费的。

难道发布的时候是免费，又马上取消了？

顺便请问大佬 回复怎么插入代码啊

**Comment by Juszoe** [comment]
@pengkaiwei 
只能检查一下日志了。
github的issue用的是markdown语法，参考[markdown](https://www.jianshu.com/p/65ab196bef04)。

**Comment by predest** [comment]
@Juszoe 刚刚测试了一下，发现加上seeder和leecher来过滤就不能识别免费种，免费种在Log里显示被拒绝（Remembering rejection of ‘’）。去除seeder和leecher的话，能下载种子，但是也碰到和pengkaiwei一样的问题，一些非免费种也会下载，已经登入站点一个个种子验证过的。不知道是否合适把具体的种子信息发在这里，所以先不发了，需要的话我可以私信具体的种子来甄别bug

**Comment by levenwindy** [comment]
@Juszoe  请问您是用最新版，还是V1.4 正式版？
我用最新版  2 months ago
```
discount:
  - free
  - 2xfree
```
所有报错都显示无法匹配优惠，例如
```
2021-10-09 12:17:54 VERBOSE  task                          REJECTED: [xxx] by nexusphp plugin because none does not match discount
```
-----------------------------------------
如果，删掉discount后，就变成leecher报错
```
leechers:
  min: 5
  max: 99999
  max_complete: 0.8
```
报错信息如下：
```
2021-10-09 19:03:34 VERBOSE  task                          REJECTED: [xxx] by nexusphp plugin because 0 is out of range of leecher
```
删掉leechers就报错了

**Comment by 13229896070** [comment]
@Juszoe  请问您是用最新版，还是V1.4 正式版？
我用最新版  2 months ago
```
discount:
  - free
  - 2xfree
```
所有报错都显示无法匹配优惠，例如
```
2021-10-09 12:17:54 VERBOSE  task                          REJECTED: [xxx] by nexusphp plugin because none does not match discount
```
-----------------------------------------
如果，删掉discount后，就变成leecher报错
```
leechers:
  min: 5
  max: 99999
  max_complete: 0.8
```
报错信息如下：
```
2021-10-09 19:03:34 VERBOSE  task                          REJECTED: [xxx] by nexusphp plugin because 0 is out of range of leecher
```
删掉leechers就正常了
