### ISSUE TITLE
[HDC]Can't access the site. Your cookie may be wrong

### ISSUE THREAD

**Issue by coswell** [Juszoe/flexget-nexusphp#73]
```
nexusphp:
  cookie: '***'
  discount:
   - free
   - 2xfree
  left-time: 5 hours
  hr: no
```
我订阅的free和2xfree，看日志运行一会儿后就报错了"Can't access the site. Your cookie may be wrong!"
但是我用浏览器看cookie是没有失效的。
然后我发现报错后先用网页访问一遍hdc，flexget就又可以正常运行一段时间了...就很迷
