### ISSUE TITLE
btschool失效

### ISSUE THREAD

**Issue by hexoctal-sur** [Juszoe/flexget-nexusphp#78]
昨天晚上突然发现服务器已经好久没有添加新种，因为此前也有类似的抽风现象就没管，今天查看remeber_rejected发现拒绝理由均为"None does not match discount"，尝试自己适配之后还是不能下载

```
templates:
  freespace:
    free_space:
      path: /home/TrDownloads/
      space: 102400
  tr:
    transmission:
      path: /home/TrDownloads/
      host: localhost
      port: xxxx
      username: 'xxxxx'
      password: 'xxxxx'
      max_up_speed: 20480
  size:
    content_size:
      min: 0
      max: 51200
      strict: no

# 任务
tasks:
  btschool:
    rss: 
      url: xxx
      other_fields:
        - link
    template: tr
    content_size:
      min: 0
      max: 51200
      strict: no
    transmission:
      max_up_speed: 20480
    nexusphp:
      adapter:
        free: free
        2xfree: twoupfree
      cookie: 'xxx'
      discount:
        - free
        - 2xfree
      seeders:
        max: 10
      max_up_speed: 20480

web_server:
  port: xxxx
  web_ui: yes

schedules: yes
schedules:
  - tasks: [btschool]
    interval:
      minutes: 2
```
![QQ截图20211115160231](https://user-images.githubusercontent.com/13842432/141744352-dd393888-7b7a-4c8e-aa55-a66f13e6cfe7.jpg)
![QQ截图20211115160505](https://user-images.githubusercontent.com/13842432/141744489-774e20c6-a754-474a-b0ac-404bb2495529.jpg)
